# Generated by Django 3.1 on 2020-08-24 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.TextField(max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ScriptInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputText', models.TextField(max_length=2000, null=True)),
                ('user_that_input', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.datascript')),
            ],
        ),
    ]
